[package]
name = "subxt-codegen"
version = "0.24.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

license = "Apache-2.0 OR GPL-3.0"
repository = "https://github.com/paritytech/subxt"
documentation = "https://docs.rs/subxt-codegen"
homepage = "https://www.parity.io/"
description = "Generate an API for interacting with a substrate node from FRAME metadata"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "full", "bit-vec"] }
darling = "0.14.0"
frame-metadata = "15.0.0"
heck = "0.4.0"
proc-macro2 = "1.0.24"
proc-macro-error = "1.0.4"
quote = "1.0.8"
syn = "1.0.58"
scale-info = { version = "2.0.0", features = ["bit-vec"] }
subxt-metadata = { version = "0.24.0", path = "../metadata" }
jsonrpsee = { version = "0.16.0", features = ["async-client", "client-ws-transport", "http-client"] }
hex = "0.4.3"
tokio = { version = "1.8", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
bitvec = { version = "1.0.0", default-features = false, features = ["alloc"] }
pretty_assertions = "1.0.0"
